name: Mirror to Paperlight

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Paperlight GitHub
        env:
          TOKEN: ${{ secrets.PAPERLIGHT_TOKEN }}
        run: |
          git remote add paperlight https://paperlight-ai:${TOKEN}@github.com/paperlight-ai/agentos.git
          git push paperlight main --force
